#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 3 ]]; then
  echo "Usage: $0 <platform> <problem_id> <user_id> [title]"
  echo "Example: $0 boj 1000 alice \"A+B\""
  exit 1
fi

platform="$1"
problem_id="$2"
user_id="$3"
title="${4:-}"

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

problem_dir="$repo_root/archive/$platform/$problem_id"
user_dir="$problem_dir/$user_id"
readme_md="$user_dir/README.md"
template_problem="$repo_root/templates/problem.md"

mkdir -p "$user_dir"

if [[ ! -f "$readme_md" ]]; then
  cp "$template_problem" "$readme_md"
  {
    echo ""
    echo "<!-- Generated by scripts/new-problem.sh -->"
    echo "- Platform: $platform"
    echo "- Problem ID: $problem_id"
    echo "- User ID: $user_id"
    if [[ -n "$title" ]]; then
      echo "- Title: $title"
    fi
  } >> "$readme_md"
fi

echo "Created/verified: $user_dir"
